### ISSUE TITLE
HackRF Device İnstallation Error

### ISSUE THREAD

**Issue by nbgok** [jvde-github/AIS-catcher#12]
Hi Jasper, 
When I install the latest update/release I get error to "HACKRF: not found." (As seen in the link: https://imgur.com/dj7Eydh )
I want to know if you've seen this error before or it's my fault.
Thank you,

**Comment by jvde-github** [comment]
Hi, thanks for sharing.

I recognize this problem from the Raspberry Pi and made a small update to the cmake file that hopefully fixes it. Can you check if this resolves the issue you are having? 

Somehow the package configuration for the Pi does not return the correct location of the libhackrf include files. I have added them manually to the list of directories to search in.  Not very elegant but hopefully it might resolve your issue.

Please let me know.

Thanks! Jasper

**Comment by nbgok** [comment]
After the update, error was solved. 
Thanks for your attention.
