### ISSUE TITLE
Summary page data inaccurate

### ISSUE THREAD

**Issue by g7ruh** [jvde-github/AIS-catcher#137]
Jasper,

When viewing the Summary page on the Pi program (app or web), all the totals are cumulative, from either start of program or, if a file is used to store historical data, from when that file was created.

The data on this page really needs to be reset at a known point (at start of program or at a user requested time) to be really useful. Displaying totals since 'stats.bin' file creation date is not meaningful, while the program is running it logs data. When it is not running, there is no data. When it is restarted, there is a gap in data collection. meaningful on a graph but not on the Summary page.

The Summary page starting from zero is more helpful as it helps in assessing changes to setup or configuration options.

Because I use the file to store history for the plots page in the Pi program (and find it very useful), is it possible to have the Summary page start from zero at program start time and have a user reset on demand? This is how the Android App works and having the 'clear' option allows me to see run time especially for testing. Having used the Summary page like this on Android, is it possible to have the same functionality on the Pi version? 

We still need to keep the history (optionally using filename.bin):

The Plots page is accurate as it is using the historical data in a graph providing the picture over time (seconds, minutes, hours, days) and is very helpful in spotting trends. I use the frequency shift / signal level (both per minute) to help calibrate a new dongle and set optimum gain, for example.

Thanks, Roger

**Comment by Taxom** [comment]
Can you please add a plot with number of vessels?

**Comment by g7ruh** [comment]
Jasper,

Please can you add total number of vessels currently on the ships list to the map page. That is the only thing missing that I still run OpenCPN for.

![image](https://github.com/jvde-github/AIS-catcher/assets/5949609/ad21fa12-9059-4c88-9996-5966a75122f1)

I would suggest bottom right near the settings menu.

OK that you see the totals as an enhancement, 

thanks, Roger

**Comment by g7ruh** [comment]
Jasper,

that is great and agrees with OpenCPN (give or take how the programs calculate it).

![image](https://github.com/jvde-github/AIS-catcher/assets/5949609/ebc5a2c4-c7da-4e9c-b028-87cbad64f8e0)

![image](https://github.com/jvde-github/AIS-catcher/assets/5949609/072fd40d-c88a-457d-bedd-977767ef6dd8)


well it does depend on how the data is caculated. That is what I am after how many vessels (+ / - 10, even 25) is fine, I can see if it is a busy day or if there is some atmospheric enhancement or a race day out on The Solent.

AIS-catcher Pi and its web server is now my go-to solution. Thank you. I will test the Android app when it has updated.

Roger

**Comment by g7ruh** [comment]
Jasper,

I can confirm it works on Android app too. Thank you again. Big advantage over OpenCPN on Windows, the data being served from the Pi web page, the total is there instantly. Starting OpenCPN, you have to wait 10 mins or so for the total to be fairly accurate.

I rather like the upper right position, the eye just goes to the corner and the data is easy to see.

Roger

**Comment by Taxom** [comment]
Thank you!
And you can clarify, is this the total number with the base stations or only vessels?
Sincerely, Maxim.

**Comment by g7ruh** [comment]
Jasper,

Thank you that helps a lot, but a small "issue" maybe:, or could just be terminology, depending on what you aim to display.

For the "Last Hour" and "Last Day" It is the "Previous Hour" as in changing at HH:59:59.99999 (well as the hour clicks over) so in reality it is not the last hour being displayed as the data by then is say 59 minutes old. The same goes for Last Day and tonight at 22:00 the data is 22 hours old.

I am wondering if it would be more informative if it displays the 'previous 60 minutes' updated e.g. every minute, and the same for the previous 24 hours, updated every minute too.

The graphs for that data update on a regular basis.

Thanks for considering this,
Regards,

Roger

**Comment by g7ruh** [comment]
Jasper,

thanks, if English is not your mother tongue, no need to apologise!

I would prefer the way I described, keeps it in line with the graphs too.

Thanks for the continued improvement in a great app.

Let me know when you change the Android version and I will test.

regards
Roger
