### ISSUE TITLE
Different colors on contacts on map depending on last contact

### ISSUE THREAD

**Issue by flygfantast** [jvde-github/AIS-catcher#139]
Would it be possible to add the possibility to have different colors on the contacts on the map depending on it's last contact?
For example make it more and more "transparent" the closer to the 30 min limit we get since last contact. 
Maybe after 5 min, 10 min, 20 min the contact can have a lighter color, I'm thinking like MarineTraffic and VesselFinder does it.

Again thanks for a super job!

**Comment by Taxom** [comment]
Can I still ask to add a flash when receiving a message from the ship like it works on myshiptracking.com statistics page? (https://www.myshiptracking.com/stations/station?id=736)

**Comment by Taxom** [comment]
Thanks for fireworks! It is exactly what i wonted!
