### ISSUE TITLE
Time domain samples (from USRP) over ZMQ from GRC

### ISSUE THREAD

**Issue by Allan-S-Menefee** [jvde-github/AIS-catcher#15]
While investigating AIS-catcher, it appears that it only supports complex data formats. Say one wants to send it data from a USRP - which outputs real (time-domain) samples.

My current application should be equivalent to Discriminator mode, but even after converting to 48k complex and sending it out of GRC using ZMQ, I've been unable to get it to decode anything. My guess is it's the real vs (truly) complex samples, but it could be my configuration.

I can see clear message waveforms in GRC's time-domain sink when messages are received, so I know there's something there to decode.

**Comment by jvde-github** [comment]
Hi. If the switch -m 3 is used AIS-catcher assumes the input is the output from an FM discriminator with two channels, one for A and one for B. Perhaps you can contact me via email offline and share a short sample so that we can see if we can get it to work?

Thanks, Jasper
