### ISSUE TITLE
I still have some problems with the stability of feeding some AIS aggregators.

### ISSUE THREAD

**Issue by Taxom** [jvde-github/AIS-catcher#162]
I still can’t locate this problem. Both aggregators get a UDP stream from me.
myshiptracking https://www.myshiptracking.com/stations/station?id=736
![Screenshot 2023-09-05 at 13-12-26 MaxPi_AIS Stations MyShipTracking](https://github.com/jvde-github/AIS-catcher/assets/20313019/b01d9d28-c244-4880-8f9d-5a4ad6fcbce6)
marinetraffic utc time https://www.marinetraffic.com/en/ais/details/stations/23355 
![Screenshot 2023-09-05 at 13-12-09 Details for AIS station MaxPi_AIS AIS MarineTraffic](https://github.com/jvde-github/AIS-catcher/assets/20313019/de986136-13d3-4381-bfcb-c178239e6f45)
local internet traffic from Pi
![system-localhost-network_bandwidth-24h](https://github.com/jvde-github/AIS-catcher/assets/20313019/9c19618f-3268-4a12-9152-9982147740ec)
and CPU 
![system-localhost-cpu-24h](https://github.com/jvde-github/AIS-catcher/assets/20313019/5b898211-b4cf-4598-96a5-b87be458aead)

i don't see a problem with the streaming on other aggregators, but they don't have such detailed statistics. 
![Screenshot 2023-09-05 at 13-45-02 AIS Station 3319 - Canada Toronto AISHub](https://github.com/jvde-github/AIS-catcher/assets/20313019/5935eb74-2330-4781-85d9-88927237fdff)
my config
![конфиг](https://github.com/jvde-github/AIS-catcher/assets/20313019/c83569ac-ce05-4f19-a66b-273dddd13946)

**Comment by Taxom** [comment]
I changed to TCP both. I will continue monitoring it.

**Comment by otm64** [comment]
Same here for MarineTraffic. I am guessing this has to do with the recent acquisition of FleetMon & MT by Kpler. I got an e-mail from FleetMon last week saying their development team was merging with MarineTraffic's and asking me to approve them sharing my data with MT (I already feed MT). I got the vibe the trend is to migrate everything to a MT-centric product, so I cancelled my FleetMon account & stopped feeding them. No use sending data to the same ultimate organization twice. What we are experiencing may be issues processing data on the back end as they merge two systems together.

**Comment by Taxom** [comment]
Yes, it looks better, but now there is much less traffic than it was last weekend when this problem appear.
(45-50 ships now and more than 100 then)

But there are still passes at (also tcp) https://www.myshiptracking.com/stations/station?id=736
![Screenshot 2023-09-07 at 15-35-05 MaxPi_AIS Stations MyShipTracking](https://github.com/jvde-github/AIS-catcher/assets/20313019/b90bfe69-8d01-49ad-a5d4-acf10d1460a6)
But perhaps this problem is on their servers.

**Comment by Taxom** [comment]
Yesterday when i used the TCP connect from two mobiles (OpenCPN and AIS-catcher-android) and (OpenCPN), there was a lag again on the Marinetraffic statistic.  I could not make a screenshot of graph, but it was a short time like two spikes.

**Comment by g7ruh** [comment]
@Taxom 
I noticed these small gaps when I had router / ISP issues. It was when Jasper and I were tracking the UDP outage issues.

If I disconnected my data phone connection to the router and plugged it back in, nothing changed router-wise and the router re-synced in a few seconds. This gave things similar to your graph above on the MT site.

Because I had so many disconnects triggered by a noisy line, it helped Jasper to provide the Persist setting for a TCP connect, and I had a good testbed for it. 

Just an idea,
Roger

**Comment by obama** [comment]
I just tried sending data to MT and it says he got my message but the ships i found dont show up on the map. But a ship i have near me says it was updated few minutes ago, but not by me (had id turned off) so the map refreshes... ill try -P.

**Comment by Taxom** [comment]
I think that this problem can be closed as solved. I no longer see systematic problems with the feeding of AIS aggregators. Those small bursts that are still periodically happening are most likely associated with Internet providers or on aggregators' servers. If I find something, I will write here or open a new topic.
