### ISSUE TITLE
Question/feature/future - virtual stacking

### ISSUE THREAD

**Issue by sm3ulc** [jvde-github/AIS-catcher#25]
Awesome development of AIS-decoder! A thought for future. Today a very good colinear or similar AIS-antenna is rare and expensive. A interesting field to explore would be to combine signals from 2+ receivers into one. For example, to 2x RTLs need to share clock or is it enough with the RTLv3, or even the black/blue ones?

**Comment by jvde-github** [comment]
Thanks for the suggestion. Do you have an example, description or paper how that would work? Of course you can run multiple instances of AIS-catcher on one PC but that is probably not what you mean. Thanks Jasper

**Comment by sm3ulc** [comment]
No expert in signal theory so bare with me.. :)  Basically ( rtl1_I[n] + rtl2_I[n+x] ) / 2, n - number of samples, x - phase shift, 1 to some reasonable limit. This before the decimation & filtering. 

If streams decimated & filtered in parallell, then  rtl1_I[n] + rtl2_I[n] should be enough since the bitrate is only 9600?

**Comment by jvde-github** [comment]
Thanks, was planning to play a bit with multiple SDRs anyway, so will take this thought into account. Thanks again.

**Comment by jvde-github** [comment]
It is on the to-do list.. Might take a while though.
