### ISSUE TITLE
SAR helicopter incorrect country flag?

### ISSUE THREAD

**Issue by g7ruh** [jvde-github/AIS-catcher#262]
Jasper

Just noticed this:

![SAR flag wrong-query](https://github.com/jvde-github/AIS-catcher/assets/5949609/42fe2e34-585e-4342-8be6-2b7f390619c3)

which shows the wrong flag on the pop up panel and on the hover over the "vessel".

This from TAR1090, squawk 7000 as it was training not on a SAR mission:

![tar1090-CG175](https://github.com/jvde-github/AIS-catcher/assets/5949609/6eb9cc40-9242-4c4e-b37f-8521edd0f672)

Roger

**Comment by Phil353556** [comment]
hi Roger
FYI  
using one website or another this is uk costguard or bristow (https://www.bristowgroup.com/locations) ?
strange
![image](https://github.com/jvde-github/AIS-catcher/assets/64729485/d3a42289-ca44-43b5-95a3-4c600dd9074e)
![image](https://github.com/jvde-github/AIS-catcher/assets/64729485/b5d60a62-881b-4d75-b2cb-363c870e1172)
Kind regards
Philippe

**Comment by Jonboy1081** [comment]
Hi All, this has been showing like this for about a week, I think it may have had a new AIS box which is somehow coded wrong.

**Comment by g7ruh** [comment]
I can confirm it is a real helicopter, as it flies over my house, certainly not a flying ship!!: too small for that :)   It looks like the pictures above, rotor blades and red and white body. Callsign for marine frequencies CG175.


thanks @Jonboy1081 for your reply.

Roger

**Comment by g7ruh** [comment]
Jasper, 

It was just working with squawk 0023 as rescue175. Thanks for the reason why (and to @Jonboy1081 too).

I just saw it and wondered if it was a bug or human error, seems like the latter. Sorry for the "herring rouge"** as we say in England.

I will see if I can contact HM Coastguard to inform them of the data issue.

Roger 

** I will explain further if anyone is curious.

**Comment by Phil353556** [comment]
suggestion:  double check  with MMSI  and others sites to test coherency

**Comment by g7ruh** [comment]
It is OK now on MT

![image](https://github.com/jvde-github/AIS-catcher/assets/5949609/f6fb6102-4487-4402-acb7-d7c67a4dceae)

and this

![image](https://github.com/jvde-github/AIS-catcher/assets/5949609/33fa75ff-989d-42f8-a974-e41686ecff8a)



I suspect that the SAR helicopter has set the MMSI incorrectly. I have informed HM Coastguard by email.

**Comment by g7ruh** [comment]
Update 19th May 2024

Independent Primero came to Southampton and left Friday.

AIS-catcher chart swapping between vessel location and SAR helicopter location based on last received message. I guess somebody noticed it and got the MMSI fixed. I never heard back from HM Coastguard. All is well now.

![CG175-back-to-normal](https://github.com/jvde-github/AIS-catcher/assets/5949609/cb88d0d2-6fd3-4ee9-b047-c08652ad15d1)

![independent primero-202405171356](https://github.com/jvde-github/AIS-catcher/assets/5949609/426153dd-617f-4a68-ad29-04f5fc20c236)


Roger
