### ISSUE TITLE
Reordering -h output

### ISSUE THREAD

**Issue by dziban303** [jvde-github/AIS-catcher#31]
I think there may be benefit to rearranging the `-h` help output. Many programs have the switches in their help screen sorted alphabetically, which I think would be an improvement on the current arrangement since the order of options doesn't matter:

![image](https://user-images.githubusercontent.com/7931765/199114680-5f35bd54-b93f-4869-bb0b-c265db1ea1fe.png)

Keeping each of the 'sections' as-is would be fine, but within the sections, alphabetizing would make it easier to scan when looking for a specific option.

What's your take?

**Comment by jvde-github** [comment]
Like it, will do, thanks!

**Comment by jvde-github** [comment]
Done, hope it is now a bit easier to use. Thanks.

**Comment by dziban303** [comment]
Much better, thank you! Now back to troubleshooting the service performance issue I was having...
