### ISSUE TITLE
Webserver doesn’t work behind reverse web proxy

### ISSUE THREAD

**Issue by kx1t** [jvde-github/AIS-catcher#45]
Hey, this probably very premature because you’re still developing this, but your web server doesn’t appear to receive data if deployed behind a (nginx) based reverse web proxy. 

In my case: https://kx1t.com/ais -> http://10.244.136.18:90 where:
- https://kx1t.com/ais Is exposed to the internet (feel free to click it to see for yourself)
- http://10.244.136.18:90 is the internal target address on my intranet, a RPi4 that runs AIS-catcher built from the `develop` branch with argument “-N 90”

This is what it looks like when I go directly http://10.244.136.18:90
![5C67A594-D1DF-4C9A-BB03-E951EBCC6B25](https://user-images.githubusercontent.com/15090643/205499821-26087fba-9163-4f41-ac7b-f222835fff01.jpeg)

This is what it looks like from the reverse proxied address:
![4CC70198-2B0D-4637-9F39-C627F39AC803](https://user-images.githubusercontent.com/15090643/205499923-ecd9ef43-c9ae-4d13-a000-06b434225a8a.jpeg)

I’ve been on my mobile and can’t quite debug this, but I suspect that your data stream (websocket?) uses an absolute directory name (`/xxx/yyy`) instead of a relative one. Chrome inspector should be able to tell for sure.

**Comment by jvde-github** [comment]
Thanks for trying and any feedback at any stage is appreciated! I like what you are doing btw, maybe will copy this set up some day so I can monitor my station when I am not on my network. 

The code is super trivial now: the statistics are made available in a json file that the HTML page pulls from the server.
Quick test: your statistics are still made available I see on https://kx1t.com/ais/stat.json whereas the HTML page tries to fetch the data from /stat.json which results in a fetch from https://kx1t.com/stat.json.

I changed the javascript fetch to "stat.json" and uploaded that as a patch. Perhaps this solves it? 

Thanks and regards, Jasper

**Comment by kx1t** [comment]
I’ll rebuild and let you know — thanks for the very quick return and hup Holland hup :)

**Comment by kx1t** [comment]
Works well now -- see https://kx1t.com/ais
Looking forward to seeing the rest implemented - ship lists, etc.
Adding "settings" there would be a bit dangerous if the website is exposed to the world - I may have to add Authentication on the reverse web proxy if there are no further restrictions implemented with AIS-catcher

I'll close the issue - thanks again for the ultra-fast fix!
