### ISSUE TITLE
Add bearing to Ships list

### ISSUE THREAD

**Issue by g7ruh** [jvde-github/AIS-catcher#59]
Jasper,
Is it possible to add a Bearing column to the Ships list, either to left or right of 'Distance' column would be best?

I use this if I am looking for a vessel (maybe from something heard on marine voice channels) and find it easier to use distance if I know in which direction I should look.

Thanks,
Roger

**Comment by michaelgeorge001** [comment]
Hi all,
I was ready to request the same thing, but Roger beat me to it.

Thank you,
Mike

**Comment by g7ruh** [comment]
Jasper,
Just compiled the Bleeding Edge version, yes exactly what I was looking for. Thank you.

Sorry Mike! Hopefully it works for you too.

Roger
